version: "3.4"

services:
  api:
    build:
      context: .
      target: production
    volumes:
    - ./:/usr/src/server
    - /usr/src/server/node_modules
    ports:
    - 8080:8080
    env_file:
    - .env




