version: "3.4"

services:
  api:
    build:
      context: .
      target: development
    volumes:
    - ./:/usr/src/server
    - /usr/src/server/node_modules
    ports:
    - 3000:3000
    env_file:
    - ./.env.development
    command: npm run dev



        

