name: CI/CD with terraform
on:
  push:
    branches:
    - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
  PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
  PUBLIC_SSH_KEY: ${{ secrets.PUBLIC_SSH_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
      uses: actions/checkout@v2
    - name: setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
    - name: Terraform init
      id: init
      run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=$AWS_REGION"
      working-directory: ./terraform

    - name: Terraform Validate
      id: validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7
    - name: Terraform plan
      id: plan
      run: |-
        terraform plan \
        -var="region=$AWS_REGION" \
        -var="public_key=$PUBLIC_SSH_KEY" \
        -var="private_key=$PRIVATE_SSH_KEY" \
        -var="key_name=deployer-key" \
        -out=PLAN
      working-directory: ./terraform
    - name: Terraform apply
      id: apply
      run: terraform apply PLAN
      working-directory: ./terraform
        


